apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: simpledata-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 10
  - name: ng-2
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 10