---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-data
spec:
  selector:
    matchLabels:
      app: simple-data
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-data
    spec:
      containers:
      - name: simple-data
        image: ailtonmsj/simpledata:v2
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: simple-data
spec:
  selector:
    app: simple-data
  ports:
    - name: http
      port: 8080
      nodePort: 30880
  # to use minikube use the type "NodePort"
  #type: NodePort
  # to use EKS use the type "LoadBalancer"
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caller-simple-data
spec:
  selector:
    matchLabels:
      app: caller-simple-data
  replicas: 1
  template:
    metadata:
      labels:
        app: caller-simple-data
    spec:
      containers:
      - name: caller-simple-data
        image: ailtonmsj/callersimpledata:v1
        imagePullPolicy: Always